### ISSUE TITLE
Fail to run demo code

### ISSUE THREAD

**Issue by sunsystem-MSU** [blechta/fenapack#11]
I am Running Fenics 2019.1.0 version in docker, I tried to run demo_navier-stokes-pcd.py it shows an error below, not sure how to fix this issue.

```
Traceback (most recent call last):
  File "demo_navier-stokes-pcd.py", line 26, in <module>
    from fenapack import PCDKrylovSolver
  File "/home/fenics/shared/Research/MPC/MPC_dolfin/fenapack/fenapack/__init__.py", line 40, in <module>
    from fenapack.stabilization import StabilizationParameterSD
  File "/home/fenics/shared/Research/MPC/MPC_dolfin/fenapack/fenapack/stabilization.py", line 84, in <module>
    _expr = compile_cpp_code(_streamline_diffusion_cpp).StabilizationParameterSD
  File "/usr/local/lib/python3.6/dist-packages/dolfin/jit/pybind11jit.py", line 96, in compile_cpp_code
    generate=jit_generate)
  File "/usr/local/lib/python3.6/dist-packages/dolfin/jit/jit.py", line 47, in mpi_jit
    return local_jit(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dolfin/jit/jit.py", line 103, in dijitso_jit
    return dijitso.jit(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dijitso/jit.py", line 212, in jit
    lib = load_library(signature, cache_params)
  File "/usr/local/lib/python3.6/dist-packages/dijitso/cache.py", line 363, in load_library
    lib = __import__(signature)
ImportError: generic_type: type "StabilizationParameterSD" referenced unknown base type "dolfin::Expression"
```

**Comment by blechta** [comment]
I'm not able to reproduce the problem. If I am in the repository root of FENaPack master, I do:
```
fenicsproject pull stable
fenicsproject run stable
```
and in the container
```
pip3 install --user .
cd demo/navier-stokes-pcd/
python3 demo_navier-stokes-pcd.py
```
which runs fine.

Maybe try to clean your JIT cache
```
fenicsproject clean-cache stable
```

**Comment by blechta** [comment]
No response in over a month so closing
